[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/portal-ofertas"
  to = "/portal-ofertas.html"
  status = 200

[[redirects]]
  from = "/ofertas"
  to = "/ofertas.html"
  status = 200
